### PR TITLE
Unsupported locales fix

### PR DESCRIPTION
**Pull request by yasen-mailjet**
For some reason the diff does not display correctly. Apology.

### CODE REVIEW

**Comment by Quetzacoalt91** [comment]
Hi @yasen-mailjet,

Can you please remove the file *config_fr.xml* ? Thanks

**Comment by Quetzacoalt91** [comment]
Hi @yasen-mailjet,

Why do you add Spanish and German version of your emails if your write them in French ?

**Comment by yasen-mailjet** [comment]
Hi @Quetzacoalt91 Fixed the issues you mentioned. Please review. Thank you.

**Comment by yasen-mailjet** [comment]
No more commits...

**Comment by Quetzacoalt91** [comment]
Hi @yasen-mailjet,

So these German and Spanish versions will be in English ? Not in the specified language ?

**Comment by aneliyaB** [comment]
Hey Thomas,

Yes, currently we haven't German and Spanish versions, those files were created so we can easily detect ES and DE locale and to present respectively this site version if the user tries to create a new account.

**Comment by Quetzacoalt91** [comment]
Hi @yasen-mailjet & @aneliyaB ,

All right then, your PR has just been merged and the changes will be available from tomorrow.
Thanks !

Best regards

**Pull request merged**
